# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emailaddress', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='id',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhoodid',
            field=models.CharField(blank=True, db_column='neighbourhoodID', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='business',
            name='neighbourhoodid',
            field=models.ForeignKey(blank=True, db_column='neighbourhoodID', null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.Neighbourhood'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
