# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20180319_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.AddField(
            model_name='business',
            name='businessid',
            field=models.CharField(blank=True, db_column='businessID', max_length=255, primary_key=True, serialize=False),
        ),
    ]
